[package]
name = "jakar-tree"
version = "0.5.0"
authors = ["Siebencorgie <siebencorgie@googlemail.com>"]

[dependencies]

[[example]]
name = "simple"
path = "examples/src/store_and_read.rs"

[[example]]
name = "merge"
path = "examples/src/tree_merge.rs"
